import React from 'react';

export default function PrivacyPolicy() {
  return (
    <div
      className="privacy-policy-container"
      style={{
        maxWidth: '800px',
        margin: '0 auto',
        padding: '40px 24px',
        fontFamily: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
        lineHeight: 1.6,
        color: '#333',
      }}
    >
      <h1
        style={{
          fontSize: '28px',
          fontWeight: 600,
          marginBottom: '24px',
          color: '#4338ca',
        }}
      >
        Privacy Policy
      </h1>

      <p style={{ marginBottom: '16px' }}>
        <strong>Last Updated:</strong> May 9, 2025
      </p>

      <p style={{ marginBottom: '16px' }}>
        Xavigate International ("we," "our," or "us") is committed to protecting your privacy. This
        Privacy Policy explains how your personal information is collected, used, and disclosed by
        Xavigate International.
      </p>

      <p style={{ marginBottom: '16px' }}>
        This Privacy Policy applies to our website, and its associated subdomains (collectively, our
        "Service") alongside our application, Xavigate. By accessing or using our Service, you
        signify that you have read, understood, and agree to our collection, storage, use, and
        disclosure of your personal information as described in this Privacy Policy and our Terms of
        Service.
      </p>

      <h2
        style={{
          fontSize: '22px',
          fontWeight: 600,
          marginTop: '32px',
          marginBottom: '16px',
          color: '#333',
        }}
      >
        Definitions and key terms
      </h2>

      <p style={{ marginBottom: '16px' }}>
        To help explain things as clearly as possible in this Privacy Policy, every time any of
        these terms are referenced, are strictly defined as:
      </p>

      <ul
        style={{
          marginBottom: '16px',
          paddingLeft: '24px',
          listStyleType: 'disc',
        }}
      >
        <li style={{ marginBottom: '8px' }}>
          <strong>Cookie:</strong> small amount of data generated by a website and saved by your web
          browser. It is used to identify your browser, provide analytics, remember information
          about you such as your language preference or login information.
        </li>
        <li style={{ marginBottom: '8px' }}>
          <strong>Company:</strong> when this policy mentions "Company," "we," "us," or "our," it
          refers to Xavigate International, that is responsible for your information under this
          Privacy Policy.
        </li>
        <li style={{ marginBottom: '8px' }}>
          <strong>Personal Data:</strong> any information that directly, indirectly, or in
          connection with other information — including a personal identification number — allows
          for the identification or identifiability of a natural person.
        </li>
        <li style={{ marginBottom: '8px' }}>
          <strong>Service:</strong> refers to the website, application, and any related services
          provided by Xavigate International.
        </li>
        <li style={{ marginBottom: '8px' }}>
          <strong>Third-party service:</strong> refers to advertisers, contest sponsors, promotional
          and marketing partners, and others who provide our content or whose products or services
          we think may interest you.
        </li>
        <li style={{ marginBottom: '8px' }}>
          <strong>You:</strong> a person or entity that is registered with Xavigate to use the
          Services.
        </li>
      </ul>

      <h2
        style={{
          fontSize: '22px',
          fontWeight: 600,
          marginTop: '32px',
          marginBottom: '16px',
          color: '#333',
        }}
      >
        Information we collect
      </h2>

      <p style={{ marginBottom: '16px' }}>
        We collect information from you when you visit our application, register on our site, place
        an order, subscribe to our newsletter, respond to a survey or fill out a form.
      </p>

      <ul
        style={{
          marginBottom: '16px',
          paddingLeft: '24px',
          listStyleType: 'disc',
        }}
      >
        <li style={{ marginBottom: '8px' }}>Name / Username</li>
        <li style={{ marginBottom: '8px' }}>Email Addresses</li>
        <li style={{ marginBottom: '8px' }}>Password</li>
        <li style={{ marginBottom: '8px' }}>Survey Responses / Form Submissions</li>
        <li style={{ marginBottom: '8px' }}>Usage Data</li>
      </ul>

      <h2
        style={{
          fontSize: '22px',
          fontWeight: 600,
          marginTop: '32px',
          marginBottom: '16px',
          color: '#333',
        }}
      >
        How we use your information
      </h2>

      <p style={{ marginBottom: '16px' }}>
        We use the information we collect in various ways, including to:
      </p>

      <ul
        style={{
          marginBottom: '16px',
          paddingLeft: '24px',
          listStyleType: 'disc',
        }}
      >
        <li style={{ marginBottom: '8px' }}>Provide, operate, and maintain our application</li>
        <li style={{ marginBottom: '8px' }}>Improve, personalize, and expand our application</li>
        <li style={{ marginBottom: '8px' }}>Understand and analyze how you use our application</li>
        <li style={{ marginBottom: '8px' }}>
          Develop new products, services, features, and functionality
        </li>
        <li style={{ marginBottom: '8px' }}>
          Communicate with you, either directly or through one of our partners, including for
          customer service, to provide you with updates and other information relating to the
          application, and for marketing and promotional purposes
        </li>
        <li style={{ marginBottom: '8px' }}>Send you emails</li>
        <li style={{ marginBottom: '8px' }}>Find and prevent fraud</li>
      </ul>

      <h2
        style={{
          fontSize: '22px',
          fontWeight: 600,
          marginTop: '32px',
          marginBottom: '16px',
          color: '#333',
        }}
      >
        Log Files
      </h2>

      <p style={{ marginBottom: '16px' }}>
        Xavigate follows a standard procedure of using log files. These files log visitors when they
        visit websites. All hosting companies do this and a part of hosting services' analytics. The
        information collected by log files include internet protocol (IP) addresses, browser type,
        Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the
        number of clicks. These are not linked to any information that is personally identifiable.
        The purpose of the information is for analyzing trends, administering the site, tracking
        users' movement on the website, and gathering demographic information.
      </p>

      <h2
        style={{
          fontSize: '22px',
          fontWeight: 600,
          marginTop: '32px',
          marginBottom: '16px',
          color: '#333',
        }}
      >
        Cookies and Web Beacons
      </h2>

      <p style={{ marginBottom: '16px' }}>
        Like any other website, Xavigate uses 'cookies'. These cookies are used to store information
        including visitors' preferences, and the pages on the website that the visitor accessed or
        visited. The information is used to optimize the users' experience by customizing our web
        page content based on visitors' browser type and/or other information.
      </p>

      <h2
        style={{
          fontSize: '22px',
          fontWeight: 600,
          marginTop: '32px',
          marginBottom: '16px',
          color: '#333',
        }}
      >
        Third-Party Privacy Policies
      </h2>

      <p style={{ marginBottom: '16px' }}>
        Xavigate's Privacy Policy does not apply to other advertisers or websites. Thus, we are
        advising you to consult the respective Privacy Policies of these third-party ad servers for
        more detailed information. It may include their practices and instructions about how to
        opt-out of certain options.
      </p>

      <h2
        style={{
          fontSize: '22px',
          fontWeight: 600,
          marginTop: '32px',
          marginBottom: '16px',
          color: '#333',
        }}
      >
        Children's Information
      </h2>

      <p style={{ marginBottom: '16px' }}>
        Another part of our priority is adding protection for children while using the internet. We
        encourage parents and guardians to observe, participate in, and/or monitor and guide their
        online activity.
      </p>

      <p style={{ marginBottom: '16px' }}>
        Xavigate does not knowingly collect any Personal Identifiable Information from children
        under the age of 13. If you think that your child provided this kind of information on our
        website, we strongly encourage you to contact us immediately and we will do our best efforts
        to promptly remove such information from our records.
      </p>

      <h2
        style={{
          fontSize: '22px',
          fontWeight: 600,
          marginTop: '32px',
          marginBottom: '16px',
          color: '#333',
        }}
      >
        Changes to This Privacy Policy
      </h2>

      <p style={{ marginBottom: '16px' }}>
        We may update our Privacy Policy from time to time. Thus, we advise you to review this page
        periodically for any changes. We will notify you of any changes by posting the new Privacy
        Policy on this page. These changes are effective immediately, after they are posted on this
        page.
      </p>

      <h2
        style={{
          fontSize: '22px',
          fontWeight: 600,
          marginTop: '32px',
          marginBottom: '16px',
          color: '#333',
        }}
      >
        Contact Us
      </h2>

      <p style={{ marginBottom: '16px' }}>
        If you have any questions or suggestions about our Privacy Policy, do not hesitate to
        contact us at privacy@xavigate.com.
      </p>
    </div>
  );
}

// This export statement ensures the file is treated as a module
export {};
